In [1]:
import numpy as np
print(np.ones((3,)))

[1. 1. 1.]


In [2]:
print(np.ones((2,3))+np.ones((3,)))

[[2. 2. 2.]
 [2. 2. 2.]]


In [3]:
print(np.ones((2,3))+np.ones((1,3)))

[[2. 2. 2.]
 [2. 2. 2.]]


In [4]:
print(np.ones((4,3))+np.ones((2,3,)))

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [5]:
a1=np.empty((3,4), dtype=np.float32)
print(a1)

[[0.    1.875 0.    1.875]
 [0.    1.875 0.    1.875]
 [0.    1.875 0.    1.875]]


In [6]:
print(a1.size)

12


In [7]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.sum(a1))
print(np.sum(a1,axis=1))  #rowwise
print(np.sum(a1,axis=0))  #columnwise

45
[ 6 15 24]
[12 15 18]


In [9]:
print(np.amin(a1))
print(np.amin(a1,axis=1))  #rowwise
print(np.amin(a1,axis=0))  #columnwise

1
[1 4 7]
[1 2 3]


In [10]:
print(np.amax(a1))
print(np.amax(a1,axis=1))  #rowwise
print(np.amax(a1,axis=0))  #columnwise

9
[3 6 9]
[7 8 9]


In [11]:
print(a1)
print(np.mean(a1))
print(np.mean(a1,axis=1))  #rowwise
print(np.mean(a1,axis=0))  #columnwise

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[2. 5. 8.]
[4. 5. 6.]


In [12]:
print(a1)
print(np.median(a1))
print(np.median(a1,axis=1))  #rowwise
print(np.median(a1,axis=0))  #columnwise

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[2. 5. 8.]
[4. 5. 6.]


In [13]:
print(np.average(a1))

5.0


In [14]:
print(np.average(a1,axis=1, weights=[1,2,2]))

[2.2 5.2 8.2]


In [15]:
print(np.average(a1,axis=0, weights=[1,2,2]))

[4.6 5.6 6.6]


In [16]:
print(np.sum(np.ones((2,4)),axis=0))

[2. 2. 2. 2.]


In [17]:
print(np.std(a1))
print(np.std(a1,axis=0))
print(np.std(a1,axis=1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [18]:
print(np.var(a1))
print(np.var(a1,axis=0))
print(np.var(a1,axis=1))

6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


In [19]:
print(a1)
print(np.ptp(a1))
print(np.ptp(a1, axis=1)) # 1 means row
print(np.ptp(a1, axis=0)) # 0 means column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[2 2 2]
[6 6 6]


In [20]:
print(np.reshape(a1,(9,)))

[1 2 3 4 5 6 7 8 9]


In [21]:
a2=np.random.random((3,4))
print(a2)

[[0.40123548 0.70272711 0.804065   0.85319501]
 [0.3954487  0.11716922 0.77541392 0.63701266]
 [0.53266418 0.49981298 0.33159031 0.99037957]]


In [22]:
print(np.reshape(a2,(6,2)))

[[0.40123548 0.70272711]
 [0.804065   0.85319501]
 [0.3954487  0.11716922]
 [0.77541392 0.63701266]
 [0.53266418 0.49981298]
 [0.33159031 0.99037957]]


In [23]:
print(np.resize(a2,(6,1)))

[[0.40123548]
 [0.70272711]
 [0.804065  ]
 [0.85319501]
 [0.3954487 ]
 [0.11716922]]


In [24]:
a5=np.random.random((4,5))
print(np.average(a5,axis=0,weights=[1,2,1,1]))

[0.62834662 0.47778412 0.58762162 0.66152968 0.49809232]


In [25]:
a6=np.reshape(np.arange(30),(6,5))
for i in range(a6.shape[1]):
    print(i+1,end=" ")

1 2 3 4 5 