In [1]:
l=[1,2,3]
l1=[4,5,6]
print(l1+l)

[4, 5, 6, 1, 2, 3]


In [2]:
print(l1*3)

[4, 5, 6, 4, 5, 6, 4, 5, 6]


In [3]:
import numpy as np

In [5]:
#pip install numpy
a1=np.array([1,2,3])
print(a1, type(a1))

[1 2 3] <class 'numpy.ndarray'>


In [6]:
print(a1.shape)

(3,)


In [8]:
a2=np.array((4,5,6))
print(a2)

[4 5 6]


In [9]:
print(a2.itemsize)

4


In [10]:
print(a2.dtype)

int32


In [13]:
a3=np.arange(10)
print(a3)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
a4=np.linspace(1,20,7)
print(a4)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [15]:
a_2d=np.array([[1,2,3],[4,5,6]])
print(a_2d)

[[1 2 3]
 [4 5 6]]


In [16]:
print(a_2d.shape)

(2, 3)


In [17]:
a_2d[1,1]

5

In [19]:
a_2d[-2,-2]

2

In [20]:
a_2d[:,1:3]

array([[2, 3],
       [5, 6]])

In [23]:
a_2d_2=np.random.random((5,7))

In [22]:
print(a_2d_2[1:5:2,2::2])

[[0.1578428  0.83052035 0.82383783]
 [0.09904307 0.78151391 0.00710991]]


In [26]:
a_2d_3=np.zeros((3,4), dtype=np.int32)
print(a_2d_3,a_2d_3.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int32


In [27]:
a_2d_3=np.ones((4,3))
print(a_2d_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
a_2d_4=np.diag([1,2,3,4])
print(a_2d_4)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
a_2d_5=np.random.uniform(low=0,high=50,size=(3,4))
print(a_2d_5)

[[36.98908861  4.81311747 20.9258597  48.00429094]
 [46.41093772  4.65405293  8.65721637 28.33630508]
 [38.17318382 33.57356594 16.64920514  3.11488769]]


In [31]:
a_3d=np.array([[[1,1,],[1,1]],
              [[2,2],[2,2]],
              [[3,3],[3,3]]])
print(a_3d)

[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]]


In [32]:
a_3d[1,1,1]

2

In [34]:
print(np.array([1,2,3]+np.array([4.0,5.0,6.0])))

[5. 7. 9.]


In [35]:
print(np.array([1,2,3]-np.array([4.0,5.0,6.0])))

[-3. -3. -3.]


In [36]:
print(np.array([1,2,3]*np.array([4.0,5.0,6.0])))

[ 4. 10. 18.]


In [37]:
print(np.array([1,2,3]/np.array([4.0,5.0,6.0])))

[0.25 0.4  0.5 ]


In [42]:
print(np.add(np.array([[3,4],[1,2],[0,5]]),np.array([[1,1]])))

[[4 5]
 [2 3]
 [1 6]]


In [43]:
print(np.subtract(np.array([[3,4],[1,2],[0,5]]),np.array([[1,1]])))

[[ 2  3]
 [ 0  1]
 [-1  4]]


In [44]:
print(np.multiply(np.array([[3,4],[1,2],[0,5]]),np.array([[1,1]])))

[[3 4]
 [1 2]
 [0 5]]


In [45]:
print(np.divide(np.array([[3,4],[1,2],[0,5]]),np.array([[1,1]])))

[[3. 4.]
 [1. 2.]
 [0. 5.]]


In [46]:
a1=np.array([[1,1]])
a2=np.array([[2],[2]])
print(np.dot(a1,a2))

[[4]]
